open! Core
open! Desmos_compiler
open! Languages
open! Types

(* TODO: this file is just for my testing so feel free to delete it *)

(* let check file = *)
(*   file |> Utils.read_from_file |> Pass_check_function_defs.compile |> ok_exn *)
(*   |> Pass_extract_function_calls_and_defs.compile *)
(*   |> Pass_check_variable_scopes.compile |> ok_exn *)
(*   |> Pass_rename_local_variables.compile |> Pass_explicate_control.compile *)
(*   |> [%sexp_of: Register_func_instrs.t] |> print_s *)
(**)
(* let%expect_test "" = *)
(*   check "programs/fib_8_slow.sexp"; *)
(*   [%expect *)
(*     {| *)
(*     ((functions *)
(*       ((fib *)
(*         ((entry_label explicate_control_1_function_entry) *)
(*          (params (1rename_local_vars_0)) *)
(*          (blocks *)
(*           (((label explicate_control_1_function_entry) *)
(*             (body *)
(*              ((Call (func_name isOne) (args ((Register 1rename_local_vars_0))) *)
(*                (ret (1rename_local_vars_1))))) *)
(*             (control_flow *)
(*              (Jump *)
(*               (conds *)
(*                (((Register 1rename_local_vars_1) *)
(*                  explicate_control_3_if_statement_branch))) *)
(*               (default explicate_control_4_if_statement_else)))) *)
(*            ((label explicate_control_3_if_statement_branch) (body ()) *)
(*             (control_flow (Return (Num 1)))) *)
(*            ((label explicate_control_4_if_statement_else) *)
(*             (body *)
(*              ((Call (func_name isPositive) *)
(*                (args ((Register 1rename_local_vars_0))) *)
(*                (ret (1rename_local_vars_2))))) *)
(*             (control_flow *)
(*              (Jump *)
(*               (conds *)
(*                (((Register 1rename_local_vars_2) *)
(*                  explicate_control_6_if_statement_branch))) *)
(*               (default explicate_control_7_if_statement_else)))) *)
(*            ((label explicate_control_6_if_statement_branch) *)
(*             (body *)
(*              ((Call (func_name fib) *)
(*                (args ((Sub (Register 1rename_local_vars_0) (Num 1)))) *)
(*                (ret (1rename_local_vars_3))) *)
(*               (Call (func_name fib) *)
(*                (args ((Sub (Register 1rename_local_vars_0) (Num 2)))) *)
(*                (ret (1rename_local_vars_4))))) *)
(*             (control_flow *)
(*              (Return *)
(*               (Add (Register 1rename_local_vars_3) *)
(*                (Register 1rename_local_vars_4))))) *)
(*            ((label explicate_control_7_if_statement_else) (body ()) *)
(*             (control_flow (Return (Num 0)))) *)
(*            ((label explicate_control_5_if_statement_exit) (body ()) *)
(*             (control_flow *)
(*              (Jump (conds ()) (default explicate_control_2_if_statement_exit)))) *)
(*            ((label explicate_control_2_if_statement_exit) (body ()) *)
(*             (control_flow Exit)))))) *)
(*        (isOne *)
(*         ((entry_label explicate_control_8_function_entry) *)
(*          (params (1rename_local_vars_5)) *)
(*          (blocks *)
(*           (((label explicate_control_8_function_entry) (body ()) *)
(*             (control_flow *)
(*              (Return (Compare Eq (Register 1rename_local_vars_5) (Num 1))))))))) *)
(*        (isPositive *)
(*         ((entry_label explicate_control_9_function_entry) *)
(*          (params (1rename_local_vars_6)) *)
(*          (blocks *)
(*           (((label explicate_control_9_function_entry) (body ()) *)
(*             (control_flow *)
(*              (Return (Compare Gt (Register 1rename_local_vars_6) (Num 0))))))))))) *)
(*      (main *)
(*       (((label explicate_control_0_main) *)
(*         (body *)
(*          ((Call (func_name fib) (args ((Num 8))) *)
(*            (ret (1extract_function_calls_4_call))) *)
(*           (Set n (Register 1extract_function_calls_4_call)))) *)
(*         (control_flow Exit)))) *)
(*      (registers (1extract_function_calls_4_call n))) *)
(*     |}] *)
