open! Core
open Desmos_compiler
open Languages
(* open Types *)
(* open Desmos_virtual_machine *)

(* this also runs sanitize registers in order to print js output but that is a pretty trivial pass so it should be fine *)

let compile prog =
  prog |> Utils.read_from_str |> Cumulative_passes.sanitize_register_names
  |> ok_exn

let print_sexp compiled =
  compiled |> [%sexp_of: [ `Sanitized ] Desmos_output.t] |> print_s

let print_js compiled =
  compiled |> Desmos_output.to_pastable_javascript |> print_endline

let%expect_test "0 instructions" =
  let prog = compile {| |} in
  print_sexp prog;
  [%expect
    {|
    ((program_action
      ((conds (((Eq (Register 00pc) (Num 0)) ((00pc (Num -1))))))
       (default ((00pc (Register 00pc))))))
     (init_registers
      ((00link (Num 1.2345)) (200linkStack (ListLiteral ((Num 5.4321))))
       (00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321))))
       (00ret (Num 1.2345)) (200retStack (ListLiteral ((Num 5.4321))))))
     (info Sanitized))
    |}];
  print_js prog;
  [%expect
    {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00link}=1.2345"}, {latex: "R_{200linkStack}=\\left[5.4321\\right]"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{00ret}=1.2345"}, {latex: "R_{200retStack}=\\left[5.4321\\right]"}]) |}]

(* let%expect_test "multiple instructions" = *)
(*   let prog = *)
(*     let a = Register.of_string "a" in *)
(*     let b = Register.of_string "b" in *)
(*     compile *)
(*       { *)
(*         main = *)
(*           [ *)
(*             { *)
(*               label = Label.of_string "main"; *)
(*               body = *)
(*                 [ *)
(*                   Instruction [ (a, Set (Num 1.)); (b, Set (Num 2.)) ]; *)
(*                   Instruction [ (a, Set (Register a)) ]; *)
(*                   Exit; *)
(*                 ]; *)
(*             }; *)
(*           ]; *)
(*         registers = *)
(*           Register.Map.of_alist_exn *)
(*             [ (program_counter_reg, Num 0.); (a, Num 0.); (b, Num 0.) ]; *)
(*       } *)
(*   in *)
(*   print_sexp prog; *)
(*   [%expect *)
(*     {| *)
(*     ((program_action *)
(*       ((conds *)
(*         (((Eq (Register 00pc) (Num 0)) ((a (Num 1)) (b (Num 2)))) *)
(*          ((Eq (Register 00pc) (Num 1)) ((a (Register a)))) *)
(*          ((Eq (Register 00pc) (Num 2)) ((00pc (Num -1)))))) *)
(*        (default ((00pc (Register 00pc)))))) *)
(*      (init_registers *)
(*       ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321)))) (a (Num 0)) *)
(*        (2aStack (ListLiteral ((Num 5.4321)))) (b (Num 0)) *)
(*        (2bStack (ListLiteral ((Num 5.4321)))))) *)
(*      (info Sanitized)) *)
(*     |}]; *)
(*   print_js prog; *)
(*   [%expect *)
(*     {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: \\left(R_{a}\\to 1, R_{b}\\to 2\\right), R_{00pc} = 1: R_{a}\\to R_{a}, R_{00pc} = 2: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{a}=0"}, {latex: "R_{2aStack}=\\left[5.4321\\right]"}, {latex: "R_{b}=0"}, {latex: "R_{2bStack}=\\left[5.4321\\right]"}]) |}] *)
(**)
(* let%expect_test "push and pop" = *)
(*   let prog = *)
(*     let a = Register.of_string "a" in *)
(*     let b = Register.of_string "b" in *)
(*     let c = Register.of_string "c" in *)
(*     let d = Register.of_string "d" in *)
(*     compile *)
(*       { *)
(*         main = *)
(*           [ *)
(*             { *)
(*               label = Label.of_string "main"; *)
(*               body = *)
(*                 [ *)
(*                   Instruction *)
(*                     [ *)
(*                       (a, Push); *)
(*                       (b, Pop); *)
(*                       (c, Set (Num 1.)); *)
(*                       (d, PushAndSet (Num 1.)); *)
(*                     ]; *)
(*                   Exit; *)
(*                 ]; *)
(*             }; *)
(*           ]; *)
(*         registers = *)
(*           Register.Map.of_alist_exn *)
(*             [ *)
(*               (program_counter_reg, Num 0.); *)
(*               (a, Num 0.); *)
(*               (b, Num 0.); *)
(*               (c, Num 0.); *)
(*               (d, Num 0.); *)
(*             ]; *)
(*       } *)
(*   in *)
(*   print_sexp prog; *)
(*   [%expect *)
(*     {| *)
(*     ((program_action *)
(*       ((conds *)
(*         (((Eq (Register 00pc) (Num 0)) *)
(*           ((2aStack (ListJoin (Register 2aStack) (Register a))) *)
(*            (b (ListIndex (Register 2bStack) (ListLength (Register 2bStack)))) *)
(*            (2bStack *)
(*             (ListSlice (Register 2bStack) (Num 1) *)
(*              (Sub (ListLength (Register 2bStack)) (Num 1)))) *)
(*            (c (Num 1)) (2dStack (ListJoin (Register 2dStack) (Register d))) *)
(*            (d (Num 1)))) *)
(*          ((Eq (Register 00pc) (Num 1)) ((00pc (Num -1)))))) *)
(*        (default ((00pc (Register 00pc)))))) *)
(*      (init_registers *)
(*       ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321)))) (a (Num 0)) *)
(*        (2aStack (ListLiteral ((Num 5.4321)))) (b (Num 0)) *)
(*        (2bStack (ListLiteral ((Num 5.4321)))) (c (Num 0)) *)
(*        (2cStack (ListLiteral ((Num 5.4321)))) (d (Num 0)) *)
(*        (2dStack (ListLiteral ((Num 5.4321)))))) *)
(*      (info Sanitized)) *)
(*     |}]; *)
(*   print_js prog; *)
(*   [%expect *)
(*     {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: \\left(R_{2aStack}\\to \\operatorname{join}\\left(R_{2aStack}, R_{a}\\right), R_{b}\\to R_{2bStack}\\left[\\operatorname{length}\\left(R_{2bStack}\\right)\\right], R_{2bStack}\\to R_{2bStack}\\left[1 ... \\left(\\operatorname{length}\\left(R_{2bStack}\\right) - 1\\right)\\right], R_{c}\\to 1, R_{2dStack}\\to \\operatorname{join}\\left(R_{2dStack}, R_{d}\\right), R_{d}\\to 1\\right), R_{00pc} = 1: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{a}=0"}, {latex: "R_{2aStack}=\\left[5.4321\\right]"}, {latex: "R_{b}=0"}, {latex: "R_{2bStack}=\\left[5.4321\\right]"}, {latex: "R_{c}=0"}, {latex: "R_{2cStack}=\\left[5.4321\\right]"}, {latex: "R_{d}=0"}, {latex: "R_{2dStack}=\\left[5.4321\\right]"}]) |}] *)
(**)
(* let%expect_test "nested if_expr" = *)
(*   let prog = *)
(*     let a = Register.of_string "a" in *)
(*     compile *)
(*       { *)
(*         main = *)
(*           [ *)
(*             { *)
(*               label = Label.of_string "main"; *)
(*               body = *)
(*                 [ *)
(*                   Instruction *)
(*                     [ *)
(*                       ( a, *)
(*                         Set *)
(*                           (If_expr *)
(*                              { *)
(*                                conds = []; *)
(*                                default = *)
(*                                  If_expr *)
(*                                    { *)
(*                                      conds = *)
(*                                        [ *)
(*                                          (Compare (Gt, Num 1., Num 1.), Num 1.); *)
(*                                          (Compare (Gt, Num 1., Num 1.), Num 2.); *)
(*                                        ]; *)
(*                                      default = Num 3.; *)
(*                                    }; *)
(*                              }) ); *)
(*                     ]; *)
(*                   Exit; *)
(*                 ]; *)
(*             }; *)
(*           ]; *)
(*         registers = *)
(*           Register.Map.of_alist_exn *)
(*             [ (program_counter_reg, Num 0.); (a, Num 0.) ]; *)
(*       } *)
(*   in *)
(*   print_sexp prog; *)
(*   [%expect *)
(*     {| *)
(*     ((program_action *)
(*       ((conds *)
(*         (((Eq (Register 00pc) (Num 0)) *)
(*           ((a *)
(*             (If_expr (conds ()) *)
(*              (default *)
(*               (If_expr *)
(*                (conds *)
(*                 (((Gt (Num 1) (Num 1)) (Num 1)) ((Gt (Num 1) (Num 1)) (Num 2)))) *)
(*                (default (Num 3)))))))) *)
(*          ((Eq (Register 00pc) (Num 1)) ((00pc (Num -1)))))) *)
(*        (default ((00pc (Register 00pc)))))) *)
(*      (init_registers *)
(*       ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321)))) (a (Num 0)) *)
(*        (2aStack (ListLiteral ((Num 5.4321)))))) *)
(*      (info Sanitized)) *)
(*     |}]; *)
(*   print_js prog; *)
(*   [%expect *)
(*     {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: R_{a}\\to \\left\\{1 > 1: 1, 1 > 1: 2, 3\\right\\}, R_{00pc} = 1: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{a}=0"}, {latex: "R_{2aStack}=\\left[5.4321\\right]"}]) |}] *)
