open! Core
open Desmos_compiler
open Languages
(* open Types *)
(* open Desmos_virtual_machine *)

(* this also runs sanitize registers in order to print js output but that is a pretty trivial pass so it should be fine *)

(* TODO brady: why did I comment this out? I can probably uncomment. *)

let compile prog =
  prog |> Utils.read_from_str |> Cumulative_passes.generate_desmos_output
  |> ok_exn

let print_sexp compiled =
  compiled |> [%sexp_of: [ `Unsanitized ] Desmos_output.t] |> print_s

let%expect_test "simple program" =
  let prog =
    compile
      {|
    (def f (x) (
      (return (??
        (x == 0) 1
        default (x * (f (x - 1)))))
    ))
  |}
  in
  print_sexp prog;
  [%expect
    {|
    ((program_action
      ((conds
        (((Eq (Register 00pc) (Num 0)) ((00pc (Num -1))))
         ((Eq (Register 00pc) (Num 1))
          ((00pc
            (If_expr (conds (((Eq (Register 1local_x_0) (Num 0)) (Num 2))))
             (default (Num 4))))))
         ((Eq (Register 00pc) (Num 2))
          ((00pc (Add (Register 00pc) (Num 1)))
           (1local_1extract_ifexpr_1_1 (Num 1))))
         ((Eq (Register 00pc) (Num 3))
          ((00pc (If_expr (conds ()) (default (Num 10))))))
         ((Eq (Register 00pc) (Num 4))
          ((00pc (Add (Register 00pc) (Num 1)))
           (21local_x_0Stack
            (ListJoin (Register 21local_x_0Stack) (Register 1local_x_0)))
           (1local_x_0 (Sub (Register 1local_x_0) (Num 1)))
           (21local_1extract_call_0_2Stack
            (ListJoin (Register 21local_1extract_call_0_2Stack)
             (Register 1local_1extract_call_0_2)))
           (21local_1extract_ifexpr_1_1Stack
            (ListJoin (Register 21local_1extract_ifexpr_1_1Stack)
             (Register 1local_1extract_ifexpr_1_1)))))
         ((Eq (Register 00pc) (Num 5))
          ((200pcStack (ListJoin (Register 200pcStack) (Num 6))) (00pc (Num 1))))
         ((Eq (Register 00pc) (Num 6))
          ((00pc (Add (Register 00pc) (Num 1)))
           (1local_1extract_call_0_2
            (ListIndex (Register 21local_1extract_call_0_2Stack)
             (ListLength (Register 21local_1extract_call_0_2Stack))))
           (21local_1extract_call_0_2Stack
            (ListSlice (Register 21local_1extract_call_0_2Stack) (Num 1)
             (Sub (ListLength (Register 21local_1extract_call_0_2Stack)) (Num 1))))
           (1local_1extract_ifexpr_1_1
            (ListIndex (Register 21local_1extract_ifexpr_1_1Stack)
             (ListLength (Register 21local_1extract_ifexpr_1_1Stack))))
           (21local_1extract_ifexpr_1_1Stack
            (ListSlice (Register 21local_1extract_ifexpr_1_1Stack) (Num 1)
             (Sub (ListLength (Register 21local_1extract_ifexpr_1_1Stack))
              (Num 1))))
           (1local_x_0
            (ListIndex (Register 21local_x_0Stack)
             (ListLength (Register 21local_x_0Stack))))
           (21local_x_0Stack
            (ListSlice (Register 21local_x_0Stack) (Num 1)
             (Sub (ListLength (Register 21local_x_0Stack)) (Num 1))))))
         ((Eq (Register 00pc) (Num 7))
          ((00pc (Add (Register 00pc) (Num 1)))
           (1local_1extract_call_0_2 (Register 00ret))))
         ((Eq (Register 00pc) (Num 8))
          ((00pc (Add (Register 00pc) (Num 1)))
           (1local_1extract_ifexpr_1_1
            (Mult (Register 1local_x_0) (Register 1local_1extract_call_0_2)))))
         ((Eq (Register 00pc) (Num 9))
          ((00pc (If_expr (conds ()) (default (Num 10))))))
         ((Eq (Register 00pc) (Num 10))
          ((00ret (Register 1local_1extract_ifexpr_1_1))
           (00pc
            (ListIndex (Register 200pcStack) (ListLength (Register 200pcStack))))
           (200pcStack
            (ListSlice (Register 200pcStack) (Num 1)
             (Sub (ListLength (Register 200pcStack)) (Num 1))))))))
       (default ((00pc (Register 00pc))))))
     (init_registers
      ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321))))
       (00ret (Num 1.2345)) (200retStack (ListLiteral ((Num 5.4321))))
       (1local_1extract_call_0_2 (Num 1.2345))
       (21local_1extract_call_0_2Stack (ListLiteral ((Num 5.4321))))
       (1local_1extract_ifexpr_1_1 (Num 1.2345))
       (21local_1extract_ifexpr_1_1Stack (ListLiteral ((Num 5.4321))))
       (1local_x_0 (Num 1.2345)) (21local_x_0Stack (ListLiteral ((Num 5.4321))))))
     (status Unsanitized))
    |}]

(* let%expect_test "multiple instructions" = *)
(*   let prog = *)
(*     let a = Register.of_string "a" in *)
(*     let b = Register.of_string "b" in *)
(*     compile *)
(*       { *)
(*         main = *)
(*           [ *)
(*             { *)
(*               label = Label.of_string "main"; *)
(*               body = *)
(*                 [ *)
(*                   Instruction [ (a, Set (Num 1.)); (b, Set (Num 2.)) ]; *)
(*                   Instruction [ (a, Set (Register a)) ]; *)
(*                   Exit; *)
(*                 ]; *)
(*             }; *)
(*           ]; *)
(*         registers = *)
(*           Register.Map.of_alist_exn *)
(*             [ (program_counter_reg, Num 0.); (a, Num 0.); (b, Num 0.) ]; *)
(*       } *)
(*   in *)
(*   print_sexp prog; *)
(*   [%expect *)
(*     {| *)
(*     ((program_action *)
(*       ((conds *)
(*         (((Eq (Register 00pc) (Num 0)) ((a (Num 1)) (b (Num 2)))) *)
(*          ((Eq (Register 00pc) (Num 1)) ((a (Register a)))) *)
(*          ((Eq (Register 00pc) (Num 2)) ((00pc (Num -1)))))) *)
(*        (default ((00pc (Register 00pc)))))) *)
(*      (init_registers *)
(*       ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321)))) (a (Num 0)) *)
(*        (2aStack (ListLiteral ((Num 5.4321)))) (b (Num 0)) *)
(*        (2bStack (ListLiteral ((Num 5.4321)))))) *)
(*      (info Sanitized)) *)
(*     |}]; *)
(*   print_js prog; *)
(*   [%expect *)
(*     {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: \\left(R_{a}\\to 1, R_{b}\\to 2\\right), R_{00pc} = 1: R_{a}\\to R_{a}, R_{00pc} = 2: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{a}=0"}, {latex: "R_{2aStack}=\\left[5.4321\\right]"}, {latex: "R_{b}=0"}, {latex: "R_{2bStack}=\\left[5.4321\\right]"}]) |}] *)
(**)
(* let%expect_test "push and pop" = *)
(*   let prog = *)
(*     let a = Register.of_string "a" in *)
(*     let b = Register.of_string "b" in *)
(*     let c = Register.of_string "c" in *)
(*     let d = Register.of_string "d" in *)
(*     compile *)
(*       { *)
(*         main = *)
(*           [ *)
(*             { *)
(*               label = Label.of_string "main"; *)
(*               body = *)
(*                 [ *)
(*                   Instruction *)
(*                     [ *)
(*                       (a, Push); *)
(*                       (b, Pop); *)
(*                       (c, Set (Num 1.)); *)
(*                       (d, PushAndSet (Num 1.)); *)
(*                     ]; *)
(*                   Exit; *)
(*                 ]; *)
(*             }; *)
(*           ]; *)
(*         registers = *)
(*           Register.Map.of_alist_exn *)
(*             [ *)
(*               (program_counter_reg, Num 0.); *)
(*               (a, Num 0.); *)
(*               (b, Num 0.); *)
(*               (c, Num 0.); *)
(*               (d, Num 0.); *)
(*             ]; *)
(*       } *)
(*   in *)
(*   print_sexp prog; *)
(*   [%expect *)
(*     {| *)
(*     ((program_action *)
(*       ((conds *)
(*         (((Eq (Register 00pc) (Num 0)) *)
(*           ((2aStack (ListJoin (Register 2aStack) (Register a))) *)
(*            (b (ListIndex (Register 2bStack) (ListLength (Register 2bStack)))) *)
(*            (2bStack *)
(*             (ListSlice (Register 2bStack) (Num 1) *)
(*              (Sub (ListLength (Register 2bStack)) (Num 1)))) *)
(*            (c (Num 1)) (2dStack (ListJoin (Register 2dStack) (Register d))) *)
(*            (d (Num 1)))) *)
(*          ((Eq (Register 00pc) (Num 1)) ((00pc (Num -1)))))) *)
(*        (default ((00pc (Register 00pc)))))) *)
(*      (init_registers *)
(*       ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321)))) (a (Num 0)) *)
(*        (2aStack (ListLiteral ((Num 5.4321)))) (b (Num 0)) *)
(*        (2bStack (ListLiteral ((Num 5.4321)))) (c (Num 0)) *)
(*        (2cStack (ListLiteral ((Num 5.4321)))) (d (Num 0)) *)
(*        (2dStack (ListLiteral ((Num 5.4321)))))) *)
(*      (info Sanitized)) *)
(*     |}]; *)
(*   print_js prog; *)
(*   [%expect *)
(*     {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: \\left(R_{2aStack}\\to \\operatorname{join}\\left(R_{2aStack}, R_{a}\\right), R_{b}\\to R_{2bStack}\\left[\\operatorname{length}\\left(R_{2bStack}\\right)\\right], R_{2bStack}\\to R_{2bStack}\\left[1 ... \\left(\\operatorname{length}\\left(R_{2bStack}\\right) - 1\\right)\\right], R_{c}\\to 1, R_{2dStack}\\to \\operatorname{join}\\left(R_{2dStack}, R_{d}\\right), R_{d}\\to 1\\right), R_{00pc} = 1: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{a}=0"}, {latex: "R_{2aStack}=\\left[5.4321\\right]"}, {latex: "R_{b}=0"}, {latex: "R_{2bStack}=\\left[5.4321\\right]"}, {latex: "R_{c}=0"}, {latex: "R_{2cStack}=\\left[5.4321\\right]"}, {latex: "R_{d}=0"}, {latex: "R_{2dStack}=\\left[5.4321\\right]"}]) |}] *)
(**)
(* let%expect_test "nested if_expr" = *)
(*   let prog = *)
(*     let a = Register.of_string "a" in *)
(*     compile *)
(*       { *)
(*         main = *)
(*           [ *)
(*             { *)
(*               label = Label.of_string "main"; *)
(*               body = *)
(*                 [ *)
(*                   Instruction *)
(*                     [ *)
(*                       ( a, *)
(*                         Set *)
(*                           (If_expr *)
(*                              { *)
(*                                conds = []; *)
(*                                default = *)
(*                                  If_expr *)
(*                                    { *)
(*                                      conds = *)
(*                                        [ *)
(*                                          (Compare (Gt, Num 1., Num 1.), Num 1.); *)
(*                                          (Compare (Gt, Num 1., Num 1.), Num 2.); *)
(*                                        ]; *)
(*                                      default = Num 3.; *)
(*                                    }; *)
(*                              }) ); *)
(*                     ]; *)
(*                   Exit; *)
(*                 ]; *)
(*             }; *)
(*           ]; *)
(*         registers = *)
(*           Register.Map.of_alist_exn *)
(*             [ (program_counter_reg, Num 0.); (a, Num 0.) ]; *)
(*       } *)
(*   in *)
(*   print_sexp prog; *)
(*   [%expect *)
(*     {| *)
(*     ((program_action *)
(*       ((conds *)
(*         (((Eq (Register 00pc) (Num 0)) *)
(*           ((a *)
(*             (If_expr (conds ()) *)
(*              (default *)
(*               (If_expr *)
(*                (conds *)
(*                 (((Gt (Num 1) (Num 1)) (Num 1)) ((Gt (Num 1) (Num 1)) (Num 2)))) *)
(*                (default (Num 3)))))))) *)
(*          ((Eq (Register 00pc) (Num 1)) ((00pc (Num -1)))))) *)
(*        (default ((00pc (Register 00pc)))))) *)
(*      (init_registers *)
(*       ((00pc (Num 0)) (200pcStack (ListLiteral ((Num 5.4321)))) (a (Num 0)) *)
(*        (2aStack (ListLiteral ((Num 5.4321)))))) *)
(*      (info Sanitized)) *)
(*     |}]; *)
(*   print_js prog; *)
(*   [%expect *)
(*     {| Calc.setExpressions([{latex: "\\left\\{R_{00pc} = 0: R_{a}\\to \\left\\{1 > 1: 1, 1 > 1: 2, 3\\right\\}, R_{00pc} = 1: R_{00pc}\\to -1, R_{00pc}\\to R_{00pc}\\right\\}"}, {latex: "R_{00pc}=0"}, {latex: "R_{200pcStack}=\\left[5.4321\\right]"}, {latex: "R_{a}=0"}, {latex: "R_{2aStack}=\\left[5.4321\\right]"}]) |}] *)
