# Created 2026-05-19 Tue 00:23
#+title: Desmos compiler
#+author: Brady Bhalla
#+filetags: :project:

A [[id:018695B3-B46D-4D51-9C93-CF242FD0A041][compiler]] for the Desmos graphing calculator. This is written in [[id:EBE88C2D-1E24-40E7-8748-835FC4F942E6][OCaml]].

I made a first version of this around sophomore year of college, but I hadn't
learned about assembly or compilers at all yet so it was pretty bad.

I am working on a new version as part of a [[id:97B0001F-6FB3-47B6-9821-D0E69DC27FDD][CS 81]] project.
* Next things to do
** Error checking passes
- function calls have correct number of args
- variable names are valid
** Reset instruction
make this yourself
** language abstraction
- move each language to its own file
- uncomment languages mli definition and add comments
- what is the deriving that makes a constructor? maybe something like fields.create?
- expose all the create functions in a For_testing submodule
** types
add types everywhere
probably require a (decl (x : int)) form (optional init value?)
functions require type info (def f ((x : int) (y : int)) : bool)

- renaming pass that renames variables declared inside of functions
- typechecking pass that errors with wrong types
- when a new register is created, need to register it correctly in the map
** Language cleanup
- parameterize each type with 'additional_exprs
  - then they all use a 'additional_exprs expr
- combine some languages to use the same (parameterized) type?
** error checking
- typecheck (if I want nice errors need to annotate first few passes with line
  and original code)
  - `Safe_global_variables C_style_extracted_functions -> (`Typechecked (Type.t
    Register_map.t)) C_style_extracted_functions Or_error
  - every scoped register is unique so we just need one global map
** lists
** compression
** things that are weird
- some types are hard to read (alias as modules?)
- do functions really need an entry_label? maybe just have the helper function
  get imported everywhere and assume it starts the same way as "main".
- desmos virutal machine doesn't need an Exit, we should be able to remove that
** Remove link register
we don't really need a link register if we have program_counter. however, it
shows up too late into the compilation so maybe sticking with link is the way to
go. I think I could just implement "link" in the pc register anyway and it would
all work out fine.

I think jumplink and return should both use the pc stacks instead of the link register stack in the make_program_counter_explicit pass
** Think about optimizations
Compression should be done in Register_stack_instrs. Within each block, you can just fold over instructions and merge them greedily.

Reordering...?
* Overview of optimizations
** Simultaneous condition evaluation
This is more of a language feature than an optimization, but whenever there are
multiple conditions (if/elif or ifexpr) Desmos can evaluate all of them at once
and figure out what to do next.

Relevant passes:
- Enforce short circuiting -- if there are function calls in the conditions then
  ensure we don't do simultaneous condition evaluation
* Emulator for Register.Set.t Desmos_virtual_machine
Used for testing without actually needing to run things in Desmos. This avoids
having to do a lot of annoying browser automation. The language is pretty close
to the Desmos_output language but is more readable so I think it will be much
easier to debug if it is the emulator target.
* [4/4] Cleanup from this week                                      :ARCHIVE:
* Overview of compiler (up to date as of 4/21)                      :ARCHIVE:
* Overview of compiler (up to date as of 4/14)                      :ARCHIVE:
